<?php

namespace Mparaiso\User\Repository;

use Doctrine\ORM\EntityRepository;
use Mparaiso\User\Entity\Role;
use Mparaiso\User\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

    function register(User $user) {
        $role_user = $this->_em->getRepository("Mparaiso\User\Entity\Role")->findOneBy(array('role' => 'ROLE_USER'));
        $user->addRole($role_user);
        $user->setAccountNonExpired(true);
        $user->setAccountNonLocked(true);
        $user->setCredentialsNonExpired(true);
        $user->setEnabled(true);
        $this->_em->persist($user);
        $this->_em->flush();
        return $user;
    }

}
