<?php

namespace Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DinnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DinnerRepository extends EntityRepository
{
}
