
home:
  path: /
  defaults: { _controller: "mp.rdv.dinner_controller:index" }  
  
dinner:
  prefix: /dinner
  resource: dinner.yml
  
rsvp:
  prefix: /rsvp
  resource: rsvp.yml
 # options:
   # _before_middlewares: [ Controller\DinnerController::before ]